INSERT INTO HOLIDAYS (`DAY`, REASON, TYPE, CREATED_AT,CREATED_BY)
VALUES ('Jun 12', 'Democracy Day','FEDERAL',CURDATE(),'uexcel');

INSERT INTO HOLIDAYS (`DAY`, REASON, TYPE, CREATED_AT,CREATED_BY)
VALUES ('Oct. 1', 'Independence Day','FEDERAL',CURDATE(),'uexcel');

INSERT INTO HOLIDAYS (`DAY`, REASON, TYPE, CREATED_AT,CREATED_BY)
VALUES ('Dec. 25', 'Christmas Day','FESTIVAL',CURDATE(),'uexcel');

INSERT INTO HOLIDAYS (`DAY`, REASON, TYPE, CREATED_AT,CREATED_BY)
VALUES ('May 29', 'Children''s Day','FESTIVAL',CURDATE(),'uexcel');

INSERT INTO HOLIDAYS (`DAY`, REASON, TYPE, CREATED_AT,CREATED_BY)
VALUES ('May 1', 'Labour Day','FEDERAL',CURDATE(),'uexcel');

INSERT INTO HOLIDAYS (`DAY`, REASON, TYPE, CREATED_AT,CREATED_BY)
VALUES ('Jan 1', 'New Year''s Day','FESTIVAL',CURDATE(),'uexcel');
